/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uas.stopwatch.latihan.app.view;

import com.uas.stopwatch.latihan.app.controller.JadwalController;
import com.uas.stopwatch.latihan.app.model.Latihan;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author LENOVO
 */

public class JadwalPanel extends JPanel{
    
    private JTextField namaField, durasiField, hariField;
    private JButton tambahBtn, lihatBtn;
    private JTextArea outputArea;
    
    private JadwalController<String> jadwalController;

    /**
     * Creates new form JadwalPanel
     */
    public JadwalPanel() {
        jadwalController = new JadwalController<>();
        
        setLayout(new BorderLayout());
        
        JPanel inputPanel = new JPanel(new GridLayout(4, 2));
        inputPanel.add(new JLabel("Hari:"));
        hariField = new JTextField();
        inputPanel.add(hariField);

        inputPanel.add(new JLabel("Nama Latihan:"));
        namaField = new JTextField();
        inputPanel.add(namaField);

        inputPanel.add(new JLabel("Durasi:"));
        durasiField = new JTextField();
        inputPanel.add(durasiField);

        tambahBtn = new JButton("Tambah");
        lihatBtn = new JButton("Lihat Semua");

        inputPanel.add(tambahBtn);
        inputPanel.add(lihatBtn);

        add(inputPanel, BorderLayout.NORTH);

        outputArea = new JTextArea();
        add(new JScrollPane(outputArea), BorderLayout.CENTER);

        tambahBtn.addActionListener(e -> {
            String hari = hariField.getText();
            String nama = namaField.getText();
            String durasi = durasiField.getText();

            Latihan<String> latihan = new Latihan<>(nama, durasi);
            jadwalController.tambahLatihan(hari, latihan);

            JOptionPane.showMessageDialog(this, "Latihan ditambahkan!");
        });
        
        lihatBtn.addActionListener(e -> {
            outputArea.setText(jadwalController.ambilSemuaLatihan().toString());
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
