package com.uas.stopwatch.latihan.app.view;

import com.uas.stopwatch.latihan.app.util.LocaleUtil;
import java.awt.BorderLayout;
import java.util.Locale;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class MainFrame extends JFrame {
    private JTabbedPane tabbedPane;
    private StopwatchPanel stopwatchPanel;
    private JadwalPanel jadwalPanel;
    private JComboBox<String> langCombo;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setTitle(LocaleUtil.getString("app.title"));
        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        stopwatchPanel = new StopwatchPanel();
        jadwalPanel = new JadwalPanel();

        tabbedPane = new JTabbedPane();
        tabbedPane.add(LocaleUtil.getString("tab.stopwatch"), stopwatchPanel);
        tabbedPane.add(LocaleUtil.getString("tab.schedule"), jadwalPanel);

        langCombo = new JComboBox<>(new String[]{"English", "Bahasa"});
        langCombo.addActionListener(e -> {
            String selected = (String) langCombo.getSelectedItem();
            if ("Bahasa".equals(selected)) {
                LocaleUtil.setLocale(new Locale("id"));
            } else {
                LocaleUtil.setLocale(new Locale("en"));
            }
            refreshText();
        });

        add(langCombo, BorderLayout.NORTH);
        add(tabbedPane, BorderLayout.CENTER);
    }

    private void refreshText() {
        setTitle(LocaleUtil.getString("app.title"));
        tabbedPane.setTitleAt(0, LocaleUtil.getString("tab.stopwatch"));
        tabbedPane.setTitleAt(1, LocaleUtil.getString("tab.schedule"));
        
        stopwatchPanel.updateTexts();
        jadwalPanel.updateTexts();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        SwingUtilities.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
