/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uas.stopwatch.latihan.app.view;

import com.uas.stopwatch.latihan.app.controller.TimerController;   
import com.uas.stopwatch.latihan.app.util.TimerListener;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.*;

/**
 *
 * @author LENOVO
 */

public class StopwatchPanel extends JPanel implements TimerListener {

    private JLabel timeLabel;
    private JButton startBtn, stopBtn;
    private TimerController timerController;

    public StopwatchPanel() {
        setLayout(new FlowLayout());

        timeLabel = new JLabel("00");
        timeLabel.setFont(new Font("Arial", Font.BOLD, 40));

        startBtn = new JButton("Start");
        stopBtn = new JButton("Stop");

        timerController = new TimerController(this);

        startBtn.addActionListener(e -> timerController.start(60)); // contoh: 60 detik
        stopBtn.addActionListener(e -> timerController.stop());

        add(timeLabel);
        add(startBtn);
        add(stopBtn);
    }

    @Override
    public void onTick(int seconds) {
        SwingUtilities.invokeLater(() -> timeLabel.setText(String.valueOf(seconds)));
    }

    @Override
    public void onFinish() {
        SwingUtilities.invokeLater(() -> timeLabel.setText("DONE!"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
